In [8]:
import pandas as pd
import pandas_profiling
from pandas_profiling.utils.cache import cache_file

df = pd.read_csv("/home/acc/data/boston.csv")

profile = df.profile_report(correlations={
         "pearson": {"calculate": False},
         "spearman": {"calculate": False},
         "kendall": {"calculate": False},
         "phi_k": {"calculate": False},
         "cramers": {"calculate": False},
     })

profile.to_file("/home/acc/index.html")

HBox(children=(HTML(value='Summarize dataset'), FloatProgress(value=0.0, max=22.0), HTML(value='')))

HBox(children=(HTML(value='Generate report structure'), FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(HTML(value='Render HTML'), FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(HTML(value='Export report to file'), FloatProgress(value=0.0, max=1.0), HTML(value='')))

In [9]:
df.head()

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [11]:
df.groupby('RAD').mean()

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,TAX,PTRATIO,B,LSTAT
RAD,,,,,,,,,,,,,
1.0,329.700000,0.036029,39.900000,5.066000,0.050000,0.462890,6.555850,45.025000,6.027825,291.450000,17.565000,389.273000,7.370000
2.0,114.875000,0.083285,20.416667,9.630833,0.000000,0.484917,6.649958,64.770833,4.097008,260.666667,17.291667,386.413750,10.024583
3.0,134.657895,0.097359,16.381579,4.418947,0.052632,0.452424,6.473026,49.310526,5.146492,246.078947,18.168421,392.417895,9.076053
4.0,180.954545,0.393903,14.731818,10.746636,0.072727,0.504311,6.133118,60.841818,4.433000,335.981818,19.136364,382.721273,12.199091
5.0,185.660870,0.687792,11.108696,9.759826,0.095652,0.570883,6.393157,69.223478,3.697329,331.843478,16.546957,369.192435,10.657217
6.0,281.307692,0.150054,12.980769,8.198077,0.000000,0.514846,6.104731,60.142308,4.024915,372.884615,17.815385,387.366538,12.305769
7.0,271.352941,0.150399,26.705882,5.034706,0.000000,0.441000,6.647765,40.141176,6.495859,304.411765,18.405882,388.432941,7.988235
8.0,186.500000,0.371410,6.250000,5.932500,0.208333,0.492500,6.950792,67.350000,4.410604,301.250000,17.975000,385.277500,7.960833
24.0,421.500000,12.759291,0.000000,18.100000,0.060606,0.672417,6.022152,89.805303,2.061254,666.000000,20.200000,288.089167,18.600606